name: device_preview_module
description: "this is a module for juneflow, which provides a preview of the app on different devices using the device_preview package."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/device_preview_module

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  device_preview: ^1.1.0 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true